# Generated by Django 4.2.3 on 2023-07-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musafar", "0002_song"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_link",
        ),
        migrations.RemoveField(
            model_name="song",
            name="duration",
        ),
    ]
