# Generated by Django 4.2.3 on 2023-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musafar", "0005_datas"),
    ]

    operations = [
        migrations.CreateModel(
            name="desc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dp", models.ImageField(upload_to="")),
            ],
        ),
    ]
